version: "3.8"

services:
  dotnet-api:
    build:
      context: ./Sistema-Bancario--SCRUM
      dockerfile: src/AuthServiceBanco.Api/Dockerfile
    container_name: authservice_dotnet
    restart: always
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5025
      ASPNETCORE_ENVIRONMENT: Development
      # AQUÍ DEBES PONER TU CADENA DE CONEXIÓN DE NEON
      ConnectionStrings__DefaultConnection: "TU_CADENA_DE_NEON_AQUI"
    ports:
      - "5025:5025"
    networks:
      - app-network

  node-api:
    build:
      context: ./Sistema-Bancario--SCRUM
      dockerfile: Dockerfile
    container_name: authservice_node
    restart: always
    environment:
      PORT: "3000"
      # AQUÍ DEBES PONER TU CADENA DE MONGO ATLAS (la que ya tienes)
      URI_MONGO: "mongodb+srv://..."
      JWT_SECRET: "MyVerySecretKeyForJWTTokenAuthenticationWith256Bits!"
      AUTH_SERVICE_URL: http://dotnet-api:5025/api/v1
    ports:
      - "3000:3000"
    networks:
      - app-network

# NOTA: YA NO SE DEFINEN LOS SERVICIOS 'mongodb' NI 'postgres' AQUÍ
# PORQUE AHORA ESTÁN EN LA NUBE.

networks:
  app-network:
    driver: bridge
